name: Build and Publish Wheel

on:
  push:
    tags:
      - '*'
    branches: [gh-testing]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v5
      -   name: Set up Python
          uses: actions/setup-python@v6
          with:
              python-version: ${{ matrix.python }}

      -   name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
              version: "0.8.15"

      -   name: Set up dependencies
          run: |
              uv sync --extra dev

      -   name: Build wheel
          run: |
              uv build --wheel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spade-linux-wheel
          path: dist/*.whl
